import { type Evidence, type InvestigationResult, type RunInput, getPlaybook } from "./playbooks";

const metric = (label: string, value: string, note: string) => ({ label, value, note });
const table = (title: string, columns: string[], rows: string[][]): Evidence => ({ title, source: "Illustrative teaching fixture · not measurements of the entered address", columns, rows });
export function demoEvidence(input: RunInput): InvestigationResult {
  const base: InvestigationResult = {
    tool: input.tool, status: "demo", fetchedAt: new Date().toISOString(), subject: input.tool === "signal" ? "Illustrative discovery shortlist" : input.subject, chain: input.chain,
    metrics: [], evidence: [], observations: [], conclusion: "",
    calls: getPlaybook(input.tool).endpoints.map(endpoint => ({ endpoint, status: "demo", credits: 0 })),
  };
  switch (input.tool) {
    case "wallet": return { ...base,
      metrics: [metric("Observed assets", "$18.5M", "Illustrative holdings"), metric("Activity sample", "47", "Demo transactions"), metric("Related wallets", "4", "Relationships, not ownership")],
      evidence: [ { ...table("Asset composition", ["Asset", "Value", "Share"], [["USDT", "$8.12M", "44%"], ["ETH", "$5.35M", "29%"], ["USDC", "$2.95M", "16%"], ["Other", "$2.03M", "11%"]]), bars: [{ label: "USDT", value: 44, display: "44%" }, { label: "ETH", value: 29, display: "29%" }, { label: "USDC", value: 16, display: "16%" }, { label: "Other", value: 11, display: "11%" }] },
        table("Wallet relationships", ["Counterparty", "Observed link", "Evidence"], [["Exchange deposit", "Frequent counterparty", "Repeated outbound transfers"], ["Unlabelled wallet", "First funder", "Initial funding transaction"], ["DEX router", "Contract interaction", "Swap activity"], ["Related wallet", "Shared funder", "Same source funded both"]]),
        table("Recent activity", ["Activity", "Direction", "Amount"], [["Exchange transfer", "Outbound", "1.2M USDT"], ["DEX swap", "ETH → USDC", "420 ETH"], ["Funding link", "Inbound", "Shared funding source"]]) ],
      observations: ["Stablecoins account for 60% of the illustrative holdings.", "Repeated exchange deposits and a shared funder suggest operational connections."], conclusion: "The fixture supports investigating a connected operational wallet. A shared funder alone does not prove common ownership." };
    case "trader": return { ...base,
      metrics: [metric("Realized profit", "$184.2K", "Illustrative 30-day sample"), metric("Win rate", "62%", "87 closed positions"), metric("Best token share", "71%", "Of net realized profit")],
      evidence: [{ ...table("Profit by token", ["Token", "Realized profit", "Net profit share"], [["TOKEN A", "$130.8K", "71%"], ["TOKEN B", "$38.4K", "21%"], ["TOKEN C", "$25K", "14%"], ["Other positions", "−$10K", "−6%"]]), bars: [{ label: "TOKEN A", value: 71, display: "$130.8K" }, { label: "TOKEN B", value: 21, display: "$38.4K" }, { label: "TOKEN C", value: 14, display: "$25K" }] }, table("Trading sample", ["Measure", "Evidence"], [["Closed positions", "87"], ["Winning positions", "54"], ["Profit without best token", "$53.4K"]])],
      observations: ["Removing the best token leaves $53.4K in realized profit.", "One token still explains 71% of net profit; performance is concentrated."], conclusion: "The demo trader remains profitable without the best token. This sample does not establish repeatable future performance." };
    case "token": return { ...base,
      metrics: [metric("Top 10 ownership", "47.8%", "Illustrative supply concentration"), metric("Smart Money netflow", "+$1.8M", "Illustrative 7-day flow"), metric("Exchange netflow", "+$4.1M", "Toward exchanges")],
      evidence: [table("Ownership and flows", ["Evidence", "Value", "Interpretation"], [["Top 10 holders", "47.8% of supply", "Concentrated ownership"], ["Smart Money", "+$1.8M netflow", "Accumulation in labelled cohort"], ["Exchanges", "+$4.1M netflow", "Potential sell-side availability"]]), table("Buyer / seller cohorts", ["Cohort", "Bought", "Sold"], [["Smart Money", "$3.2M", "$1.4M"], ["Other tracked wallets", "$5.1M", "$6.8M"]])],
      observations: ["Smart Money accumulation coexists with larger exchange inflows.", "Holder concentration limits how confidently the flow can be interpreted."], conclusion: "The demo evidence is mixed. Exchange inflow and concentrated ownership weaken an uncomplicated accumulation narrative." };
    case "signal": {
      const fixtures = [{ symbol: "AERO", address: "0x940181a94A35A4569E4529A3CDfB74e38FD98631", chain: "base", liquidity: 2400000, wallets: 18, net: 810000 }, { symbol: "WETH", address: "0x4200000000000000000000000000000000000006", chain: "base", liquidity: 18000000, wallets: 32, net: 2800000 }, { symbol: "THIN", address: "0x1111111111111111111111111111111111111111", chain: "base", liquidity: 48000, wallets: 2, net: 950000 }];
      const candidates = fixtures.map(f => ({ ...f, passed: f.liquidity >= input.liquidity && f.wallets >= input.smartMoney, reasons: [`Liquidity ${f.liquidity >= input.liquidity ? "passes" : "fails"}: $${f.liquidity.toLocaleString()}`, `Wallet breadth ${f.wallets >= input.smartMoney ? "passes" : "fails"}: ${f.wallets} labelled holders`, "Positive illustrative netflow; labels are not a quality guarantee"] }));
      return { ...base, chain: "base", candidates, metrics: [metric("Candidates", "3", "Illustrative Base shortlist"), metric("Passed gates", String(candidates.filter(c => c.passed).length), "Using your selected thresholds"), metric("Liquidity floor", `$${input.liquidity.toLocaleString()}`, "Minimum USD liquidity")], evidence: [table("Discovery evidence", ["Token", "Liquidity", "Smart Money wallets", "Netflow"], fixtures.map(f => [f.symbol, `$${f.liquidity.toLocaleString()}`, String(f.wallets), `$${f.net.toLocaleString()}`]))], observations: ["The thin-liquidity candidate can attract large flows without passing the breadth test.", "This fixture uses Base tokens regardless of the selected live chain."], conclusion: `${candidates.filter(c => c.passed).length} illustrative candidates pass your numeric gates. Open a token check to examine concentration and contradictory flows.` };
    }
    case "defi": return { ...base,
      metrics: [metric("Liquid / deployed", "22% / 78%", "Illustrative gross assets"), metric("Largest protocol", "43%", "Share of gross assets"), metric("Outstanding debt", "$124K", "Health factor unavailable")],
      evidence: [{ ...table("Protocol exposure", ["Location", "Gross assets", "Debt", "Rewards"], [["Wallet", "$220K", "—", "—"], ["Aave", "$430K", "$124K", "$320"], ["Uniswap", "$350K", "$0", "$1.1K"]]), bars: [{ label: "Wallet", value: 22, display: "22%" }, { label: "Aave", value: 43, display: "43%" }, { label: "Uniswap", value: 35, display: "35%" }] }, table("Chain exposure", ["Chain", "Gross assets", "Share"], [["Ethereum", "$760K", "76%"], ["Base", "$240K", "24%"]])],
      observations: ["The largest protocol holds 43% of gross assets.", "Debt is present, but the fixture provides no health factor or liquidation threshold."], conclusion: "Protocol concentration and debt deserve investigation. Available evidence cannot establish a liquidation price or safety buffer." };
  }
}
